### ISSUE TITLE
pluggin doesnt seem to allow depug output of each new window.

### ISSUE THREAD

**Issue by pyrotek45** [perfoon/Multirun#1]
Is there a way to debug the game as if you started a single window? how would i go about getting debug info when using this plugin?

**Comment by perfoon** [comment]
I agree that this would be really useful.
The best solution would be to run the first game instance regularly (as if F5 were pressed). Unfortunately, I don't know how to do that, maybe someone can help me?
There is a virtual method build() in the EditorPlugin node, but this can only be used to capture when the user is starting the game and not start it by itself.
Have I missed something or is there an alternative?

**Comment by perfoon** [comment]
This issue was fixed in the last commit.
Essentially the first instance of the game is now started in the Godot editor so it gets the debugging by default.
